# Generated by Django 3.1.6 on 2021-02-17 02:59

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_auto_20210129_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
